# Generated by Django 4.2.1 on 2023-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_conversation_collection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
